const colors = require("tailwindcss/colors");

module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{ts,html}"],
  theme: {
    extend: {
      colors: {
        app: {
          canvas: colors.slate[100],
          "canvas-dark": colors.slate[950],
          surface: colors.white,
          "surface-dark": colors.slate[900],
          "surface-soft": colors.slate[50],
          "surface-soft-dark": colors.slate[800],
          line: colors.slate[200],
          "line-strong": colors.slate[300],
          "line-dark": colors.slate[700],
          "line-dark-strong": colors.slate[600],
          field: colors.slate[300],
          "field-dark": colors.slate[600],
          text: colors.slate[900],
          "text-dark": colors.slate[100],
          "text-soft": colors.slate[600],
          "text-soft-dark": colors.slate[300],
          "text-muted": colors.slate[500],
          "text-muted-dark": colors.slate[300],
          brand: colors.blue[600],
          "brand-strong": colors.blue[700],
          "brand-soft": colors.blue[50],
          "brand-soft-dark": colors.blue[900],
          "brand-ring": colors.blue[400],
          success: colors.emerald[600],
          "success-strong": colors.emerald[700],
          "success-soft": colors.emerald[50],
          "success-soft-dark": colors.emerald[900],
          "success-line": colors.emerald[200],
          "success-line-dark": colors.emerald[500],
          "success-text": colors.emerald[700],
          "success-text-dark": colors.emerald[200],
          danger: colors.rose[600],
          "danger-strong": colors.rose[700],
          "danger-soft": colors.rose[50],
          "danger-soft-dark": colors.rose[900],
          "danger-line": colors.rose[200],
          "danger-line-dark": colors.rose[500],
          "danger-text": colors.rose[700],
          "danger-text-dark": colors.rose[200],
          warning: colors.amber[100],
          "warning-soft-dark": colors.amber[900],
          "warning-text": colors.amber[700],
          "warning-text-dark": colors.amber[200],
          "mock-soft": colors.indigo[100],
          "mock-soft-dark": colors.indigo[900],
          "mock-text": colors.indigo[700],
          "mock-text-dark": colors.indigo[200],
        },
      },
      spacing: {
        "page-x": "1rem",
        "page-x-sm": "1.5rem",
        "page-x-lg": "2rem",
        "page-y": "1.5rem",
        stack: "1.5rem",
        "stack-sm": "1rem",
        "stack-xs": "0.75rem",
        panel: "1.25rem",
        "panel-sm": "1rem",
        "panel-lg": "2rem",
        "control-x": "0.75rem",
        "control-y": "0.5rem",
        "badge-x": "0.5rem",
        "badge-y": "0.125rem",
        "badge-pill-x": "0.625rem",
        "badge-pill-y": "0.25rem",
        "cell-x": "0.5rem",
        "cell-y": "0.5rem",
      },
      borderRadius: {
        panel: "1rem",
        card: "0.75rem",
        control: "0.375rem",
      },
      boxShadow: {
        panel: "0 1px 2px 0 rgb(15 23 42 / 0.08)",
        elevated: "0 10px 24px -12px rgb(15 23 42 / 0.35)",
      },
      maxWidth: {
        layout: "80rem",
        "layout-narrow": "64rem",
        auth: "28rem",
      },
      minWidth: {
        table: "58rem",
      },
      minHeight: {
        lane: "14rem",
      },
    },
  },
};
