name = "thesis-journey-tracker"
main = "src/worker.ts"
compatibility_date = "2026-03-22"

[build]
command = "npm run build:css"
watch_dir = "src"

[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.ico"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "thesis_tracker_db"
database_id = "d6813d8a-2b7d-4761-8baa-3e821877fd00"
migrations_dir = "migrations"

[triggers]
crons = ["30 1 * * *"]

[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "thesis-journey-tracker-backup"

[vars]
BACKUP_PREFIX = "automated-backups"

[observability]
[observability.logs]
enabled = false
invocation_logs = true
